# Generated by Django 4.0.5 on 2022-06-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('united_world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_send',
            name='title',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
