# Generated by Django 4.0.5 on 2022-08-03 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('united_world', '0006_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='Options',
        ),
    ]
