# Generated by Django 4.0.5 on 2022-08-03 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('united_world', '0008_rename_title_post_ans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
