# Generated by Django 4.0.5 on 2022-10-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R1', '0003_orders_signup_profession_table_city_table_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='idd',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
