# Generated by Django 4.0.5 on 2022-09-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_lyrics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='artist_name',
            field=models.CharField(default=7, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='song_name',
            field=models.CharField(default=9, max_length=50),
            preserve_default=False,
        ),
    ]
